name: Docker Image Build

on:
  push:
    branches: [ main ] # Or your main branch name
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # If you have a requirements.txt file

      - name: Build the Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/inventory-management-server:latest . --build-arg BUILD_DATE=$(date +%Y-%m-%dT%H:%M:%SZ)
#         docker build -t your-dockerhub-username/your-image-name:latest . # Replace with your info

#      - name: Log in to Docker Hub (only needed for pushing)
#        if: github.ref == 'refs/heads/main' # Only push on merges to main
#        run: |
#          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push the Docker image (only needed for pushing)
        if: github.ref == 'refs/heads/main'
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/inventory-management-server:latest
#          docker push your-dockerhub-username/your-image-name:latest          
